#This Makefile compiles the Memory Manager and Driver for Brent Grundman's HW1
CC = gcc
FILES = Driver.c MemoryManager.c
OUT_EXE = seedy
build:	$(FILES)
	$(CC) -o $(OUT_EXE) $(FILES)
clean:
	rm -f *.o $(OUT_EXE)
all:	$(FILES)
	$(CC) -o $(OUT_EXE) $(FILES)